### ISSUE TITLE
Tensorflow and keras dependencies not met.

### ISSUE THREAD

**Issue by Utkarsh-quytech** [PIC4SeR/AcT#12]
Hey there!!
I was using python version 9.7.12 in anaconda env and even after installing the requirements.txt file i get the below error.
Any help is much appreciated!! Thanks!!
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from utils.tools import read_yaml, Logger
  File "C:\Users\Utkarsh.Singh\Documents\Utkarsh\PoseTracking\AcT\utils\tools.py", line 21, in <module>
    from tensorflow.keras.optimizers.schedules import LearningRateSchedule
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\api\_v2\keras\__init__.py", line 12, in <module>
    from keras import __version__
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\__init__.py", line 21, in <module>
    from keras import models
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\models\__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\engine\functional.py", line 26, in <module>
    from keras import backend
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\backend.py", line 34, in <module>
    from keras.engine import keras_tensor
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\engine\keras_tensor.py", line 19, in <module>
    from keras.utils import object_identity
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\utils\__init__.py", line 48, in <module>
    from keras.utils.layer_utils import get_source_inputs
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\utils\layer_utils.py", line 26, in <module>
    from keras import initializers
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\initializers\__init__.py", line 22, in <module>
    from keras.initializers import initializers_v2
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\initializers\initializers_v2.py", line 23, in <module>
    from keras.dtensor import utils
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\dtensor\__init__.py", line 22, in <module>
    from tensorflow.compat.v2.experimental import dtensor as dtensor_api
ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\tensorflow\_api\v2\compat\v2\experimental\__init__.py)

(act) C:\Users\Utkarsh.Singh\Documents\Utkarsh\PoseTracking\AcT>python main.py -b
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from utils.tools import read_yaml, Logger
  File "C:\Users\Utkarsh.Singh\Documents\Utkarsh\PoseTracking\AcT\utils\tools.py", line 21, in <module>
    from tensorflow.keras.optimizers.schedules import LearningRateSchedule
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\api\_v2\keras\__init__.py", line 12, in <module>
    from keras import __version__
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\__init__.py", line 21, in <module>
    from keras import models
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\models\__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\engine\functional.py", line 26, in <module>
    from keras import backend
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\backend.py", line 34, in <module>
    from keras.engine import keras_tensor
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\engine\keras_tensor.py", line 19, in <module>
    from keras.utils import object_identity
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\utils\__init__.py", line 48, in <module>
    from keras.utils.layer_utils import get_source_inputs
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\utils\layer_utils.py", line 26, in <module>
    from keras import initializers
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\initializers\__init__.py", line 22, in <module>
    from keras.initializers import initializers_v2
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\initializers\initializers_v2.py", line 23, in <module>
    from keras.dtensor import utils
  File "C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\keras\dtensor\__init__.py", line 22, in <module>
    from tensorflow.compat.v2.experimental import dtensor as dtensor_api
ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (C:\Users\Utkarsh.Singh\anaconda3\envs\act\lib\site-packages\tensorflow\_api\v2\compat\v2\experimental\__init__.py)

**Comment by simoneangarano** [comment]
Hi, 
What version of TF are you using?

**Comment by Utkarsh-quytech** [comment]
# Name                    Version                   Build  Channel
tensorflow                2.6.0                    pypi_0    pypi
tensorflow-addons         0.14.0                   pypi_0    pypi
tensorflow-datasets       4.4.0                    pypi_0    pypi
tensorflow-estimator      2.15.0                   pypi_0    pypi
tensorflow-metadata       1.12.0                   pypi_0    pypi

**Comment by Utkarsh-quytech** [comment]
> Hi, What version of TF are you using?

# Name                    Version                   Build  Channel
tensorflow                2.6.0                    pypi_0    pypi
tensorflow-addons         0.14.0                   pypi_0    pypi
tensorflow-datasets       4.4.0                    pypi_0    pypi
tensorflow-estimator      2.15.0                   pypi_0    pypi
tensorflow-metadata       1.12.0                   pypi_0    pypi

**Comment by simoneangarano** [comment]
Ok, this is my current environment, and everything works:

Package Version
-----------------
absl-py 1.4.0
joblib 1.2.0
matplotlib 3.7.1
mpose 1.2
numpy 1.20.3
optuna 3.2.0
pandas 2.0.1
PyYAML 6.0
scikit-learn 1.3.2
scipy 1.10.1
tensorboard 2.10.1
tensorflow 2.10.0
tensorflow-addons 0.20.0

I will update the requirements.txt file shortly. Thanks for pointing it out!

**Comment by Utkarsh-quytech** [comment]
> Ok, this is my current environment, and everything works:
> 
> ## Package Version
> absl-py 1.4.0 joblib 1.2.0 matplotlib 3.7.1 mpose 1.2 numpy 1.20.3 optuna 3.2.0 pandas 2.0.1 PyYAML 6.0 scikit-learn 1.3.2 scipy 1.10.1 tensorboard 2.10.1 tensorflow 2.10.0 tensorflow-addons 0.20.0
> 
> I will update the requirements.txt file shortly. Thanks for pointing it out!

Thanks a lot!!

**Comment by Utkarsh-quytech** [comment]
Sorry for the inconvenience but even after installing the dependencies there is following error

 UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
Traceback (most recent call last):
  File "/home/utkarsh/Documents/Utkarsh.Singh_OLD_System_DATA/Utkarsh/PoseTracking/AcT/main.py", line 38, in <module>
    tf.config.experimental.set_visible_devices(gpus[config['GPU']], 'GPU')
IndexError: list index out of range

> Ok, this is my current environment, and everything works:
> 
> ## Package Version
> absl-py 1.4.0 joblib 1.2.0 matplotlib 3.7.1 mpose 1.2 numpy 1.20.3 optuna 3.2.0 pandas 2.0.1 PyYAML 6.0 scikit-learn 1.3.2 scipy 1.10.1 tensorboard 2.10.1 tensorflow 2.10.0 tensorflow-addons 0.20.0
> 
> I will update the requirements.txt file shortly. Thanks for pointing it out!

**Comment by simoneangarano** [comment]
It's just a warning, ignore it for now.

**Comment by Utkarsh-quytech** [comment]
This is the complete output of the warning
(act) utkarsh@H4CK3R:~/Documents/Utkarsh.Singh_OLD_System_DATA/Utkarsh/PoseTracking/AcT$ python main.py -b
/home/utkarsh/anaconda3/envs/act/lib/python3.9/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
Traceback (most recent call last):
  File "/home/utkarsh/Documents/Utkarsh.Singh_OLD_System_DATA/Utkarsh/PoseTracking/AcT/main.py", line 38, in <module>
    tf.config.experimental.set_visible_devices(gpus[config['GPU']], 'GPU')
IndexError: list index out of range
(act) utkarsh@H4CK3R:~/Documents/Utkarsh.Singh_OLD_System_DATA/Utkarsh/PoseTracking/AcT$ python main.py -t
/home/utkarsh/anaconda3/envs/act/lib/python3.9/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
Traceback (most recent call last):
  File "/home/utkarsh/Documents/Utkarsh.Singh_OLD_System_DATA/Utkarsh/PoseTracking/AcT/main.py", line 38, in <module>
    tf.config.experimental.set_visible_devices(gpus[config['GPU']], 'GPU')
IndexError: list index out of range

What is the step to get inference of the final output of the model on our video??
